name: burikaigi2026_slide
description: Burikaigi2026 Slide

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.24.3"

dependencies:
  go_router: ^17.0.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.21.3+1
  freezed_annotation: ^3.1.0
  gap: ^3.0.1
  hooks_riverpod: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  freezed: ^3.2.3
  build_runner: ^2.3.2
  riverpod_generator: ^3.0.3
  pedantic_mono: any

flutter:
  uses-material-design: true

  # 画像アセットの設定
  assets:
    - assets/images/
